# -*- conf -*-

# shell=$SHELL (if set, otherwise user's default shell from /etc/passwd)
title=Terminal
font=DejaVu Sans Mono:size=11

# To change command prompt color, in ~/bashrc, uncomment force_color_prompt=yes and change variable PS1 to
# PS1='${debian_chroot:+($debian_chroot)}\[\033[01;34m\]\u@\h:\w\[\033[00m\]\$
